Repository azahar-emu/azahar, pull requests merged in 2024-07, with the labels that each got.

#258 Converts the remaining citra wiki links to archive.org snapshots till they're replaced.
  externals/glad/Readme.md
  src/android/app/src/main/res/values/strings.xml
  src/lime/lime.cpp
  src/lime_qt/configuration/configure_system.cpp
  src/lime_qt/main.cpp
Labels: size/M

#288 Fixed secondary window hotkeys not working after applying settings
  src/lime_qt/main.cpp
  src/lime_qt/main.h
Labels: bug, size/M

#292 desktop: Migrate from legacy Citra data directory to a new Lime3DS-specific data directory
  src/common/common_paths.h
  src/common/file_util.cpp
  src/common/file_util.h
  src/lime_qt/main.cpp
  src/lime_qt/main.h
Labels: enhancement, size/M

#312 Bundle Qt Wayland into Linux AppImage
  .ci/linux.sh
Labels: enhancement, size/XS

#319 Purge iOS from project codebase
  .ci/ios.sh
  .github/workflows/build.yml
  CMakeLists.txt
  CMakeModules/DownloadExternals.cmake
  src/common/common_paths.h
  src/lime_qt/CMakeLists.txt
  src/lime_qt/bootmanager.cpp
Labels: size/L
