Repository azahar-emu/azahar, pull requests merged in 2024-08, with the labels that each got.

#320 Bump MacOS CMake target to MacOS 13
  CMakeLists.txt
Labels: size/XS

#331 Fix README.md wiki redirect and add note blockquote
  README.md
Labels: size/XS

#339 Fix crash when cubemap face id is invalid
  src/video_core/rasterizer_cache/rasterizer_cache.h
Labels: bug, size/XS

#338 Allow use of frame advancing when paused
  src/lime_qt/main.cpp
  src/lime_qt/main.ui
Labels: enhancement, size/M

#354 Android: Fix buttons scale reset
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/EmulationFragment.kt
Labels: size/XS

#356 Repurposed the Report Compatibility button
  .ci/linux.sh
  .ci/macos.sh
  .ci/windows.sh
  src/lime_qt/CMakeLists.txt
  src/lime_qt/compatdb.cpp
  src/lime_qt/compatdb.h
  src/lime_qt/compatdb.ui
  src/lime_qt/main.cpp
  src/lime_qt/main.h
  src/lime_qt/main.ui
Labels: enhancement, size/L

#333 Don't tie hotkeys to only the main window
  src/lime_qt/hotkeys.cpp
  src/lime_qt/hotkeys.h
  src/lime_qt/main.cpp
Labels: enhancement, size/M

#358 qt: Fix default language not being set to the main one the system uses
  src/lime_qt/main.cpp
Labels: size/XS

#365 Added msvc vs msys2 explanation
  README.md
Labels: squash, size/XS

#382 android: Fix pause emulator button crashes
  src/android/app/src/main/jni/native.cpp
Labels: bug, size/S

#370 Refactor android code to use LargeScreen layout instead of MobileLandscape
  src/android/app/src/main/java/io/github/lime3ds/android/display/ScreenAdjustmentUtil.kt
  src/android/app/src/main/java/io/github/lime3ds/android/display/ScreenLayout.kt
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/EmulationFragment.kt
  src/android/app/src/main/jni/config.cpp
  src/android/app/src/main/res/menu/menu_landscape_screen_layout.xml
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
  src/common/settings.h
  src/core/frontend/emu_window.cpp
  src/core/frontend/framebuffer_layout.cpp
Labels: size/M, refactor

#384 Refactor Vulkan stream buffer memory type selection
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
Labels: bug, squash, size/M

#385 Store `frame_limit` config value as a double
  src/common/settings.h
Labels: enhancement, size/XS

#393 Add "Reverse Side by Side" Stereoscopic 3D mode
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
  src/common/settings.h
  src/core/frontend/emu_window.cpp
  src/lime_qt/configuration/configure_enhancements.ui
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
Labels: enhancement, size/M

#396 Android: Fix Cardboard VR and update render_3d config descriptions
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/arrays.xml
  src/lime/default_ini.h
Labels: size/XS

#399 Fix `hotkey_groups` shortcuts not being assigned correctly
  src/lime_qt/hotkeys.cpp
Labels: bug, size/XS

#400 android: Added Material You app icon
  src/android/app/src/main/res/drawable/ic_lime_monochrome.xml
  src/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
Labels: enhancement, size/M
