Repository azahar-emu/azahar, pull requests merged in 2024-10, with the labels that each got.

#477 gl_driver.cpp: Minimum OpenGLES version is actually 3.2
  src/video_core/renderer_opengl/gl_driver.cpp
Labels: size/XS

#313 android: Add game shortcuts to about game dialog
  src/android/app/src/main/java/io/github/lime3ds/android/activities/EmulationActivity.kt
  src/android/app/src/main/java/io/github/lime3ds/android/adapters/GameAdapter.kt
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/GamesFragment.kt
  src/android/app/src/main/java/io/github/lime3ds/android/model/Game.kt
  src/android/app/src/main/java/io/github/lime3ds/android/utils/DocumentsTree.kt
  src/android/app/src/main/res/drawable/ic_shortcut.xml
  src/android/app/src/main/res/layout/dialog_about_game.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/M

#504 Revert "bundle qt wayland into appimage by rtiangha (#212)"
  .ci/linux.sh
Labels: size/XS

#420 android: Add screen orientation presets to layout settings
  src/android/app/src/main/java/io/github/lime3ds/android/activities/EmulationActivity.kt
  src/android/app/src/main/java/io/github/lime3ds/android/display/ScreenAdjustmentUtil.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/EmulationFragment.kt
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/L

#441 lime_qt: Build fixes for QT 6.8
  src/lime_qt/configuration/configure_camera.cpp
  src/lime_qt/configuration/configure_cheats.cpp
  src/lime_qt/configuration/configure_layout.cpp
  src/lime_qt/debugger/ipc/recorder.cpp
Labels: bug, size/M

#404 qt: Add diagonal directional input presets for circlepad and c-stick
  src/input_common/analog_from_button.cpp
  src/lime_qt/configuration/config.cpp
  src/lime_qt/configuration/configure_input.cpp
  src/lime_qt/configuration/configure_input.h
  src/lime_qt/configuration/configure_input.ui
Labels: enhancement, size/XL

#373 Small screen position feature
  src/android/app/src/main/java/io/github/lime3ds/android/display/ScreenLayout.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/model/FloatSetting.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/model/view/SettingsItem.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/model/view/SliderSetting.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/ui/SettingsAdapter.kt
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/config.cpp
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
  src/common/settings.cpp
  src/common/settings.h
  src/core/frontend/emu_window.cpp
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
  src/core/hle/service/cam/cam.cpp
  src/core/hle/service/cam/cam.h
  src/core/hle/service/cam/cam_params.h
  src/lime_qt/camera/qt_camera_base.cpp
  src/lime_qt/configuration/config.cpp
  src/lime_qt/configuration/configure_camera.cpp
  src/lime_qt/configuration/configure_layout.cpp
  src/lime_qt/configuration/configure_layout.ui
  src/lime_qt/lime_qt.cpp
  src/lime_qt/lime_qt.h
  src/lime_qt/main.ui
  src/video_core/rasterizer_cache/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_blit_helper.cpp
Labels: enhancement, squash, size/XXL

#524 Make `lime` target utilize precompiled headers
  src/lime/CMakeLists.txt
  src/lime/precompiled_headers.h
Labels: size/S, miscellaneous

#525 lime: Help text now omits references to the SDL frontend if it is disabled
  src/lime/common_strings.h
Labels: enhancement, size/XS

#526 Disable SDL2 frontend at compile time by default
  CMakeLists.txt
Labels: enhancement, size/XS

#527 lime_qt: Use non-breaking spaces+hyphens in command output message boxes
  src/lime_qt/lime_qt.cpp
Labels: enhancement, size/XS
