Repository azahar-emu/azahar, pull requests merged in 2024-04, with the labels that each got.

#51 Android: new overlay button to swap screens
  src/android/app/src/main/java/io/github/lime3ds/android/NativeLibrary.kt
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/EmulationFragment.kt
  src/android/app/src/main/java/io/github/lime3ds/android/overlay/InputOverlay.kt
  src/android/app/src/main/res/drawable-hdpi/button_swap.png
  src/android/app/src/main/res/drawable-hdpi/button_swap_pressed.png
  src/android/app/src/main/res/drawable-xhdpi/button_swap.png
  src/android/app/src/main/res/drawable-xhdpi/button_swap_pressed.png
  src/android/app/src/main/res/drawable-xxhdpi/button_swap.png
  src/android/app/src/main/res/drawable-xxhdpi/button_swap_pressed.png
  src/android/app/src/main/res/drawable-xxxhdpi/button_swap.png
  src/android/app/src/main/res/drawable-xxxhdpi/button_swap_pressed.png
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/integers.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#69 Android overlay: possibility to adjust the scale of individual buttons
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/EmulationFragment.kt
  src/android/app/src/main/java/io/github/lime3ds/android/overlay/InputOverlay.kt
  src/android/app/src/main/res/menu/menu_overlay_options.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#91 Fix Mali GPU Performance issues on OpenGL
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: enhancement, help wanted

#87 Fix for full screen Smash Bros crash in Vulkan
  src/video_core/CMakeLists.txt
  src/video_core/custom_textures/custom_tex_manager.cpp
  src/video_core/pica/regs_texturing.h
  src/video_core/rasterizer_cache/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_texture_runtime.cpp
  src/video_core/renderer_opengl/gl_texture_runtime.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_helper.cpp
  src/video_core/renderer_vulkan/vk_blit_helper.h
  src/video_core/renderer_vulkan/vk_common.h
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.h
  src/video_core/renderer_vulkan/vk_descriptor_update_queue.cpp
  src/video_core/renderer_vulkan/vk_descriptor_update_queue.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_platform.cpp
  src/video_core/renderer_vulkan/vk_present_window.cpp
  src/video_core/renderer_vulkan/vk_present_window.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_render_manager.cpp
  src/video_core/renderer_vulkan/vk_render_manager.h
  src/video_core/renderer_vulkan/vk_resource_pool.cpp
  src/video_core/renderer_vulkan/vk_resource_pool.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_shader_util.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_texture_runtime.cpp
  src/video_core/renderer_vulkan/vk_texture_runtime.h
  src/video_core/shader/generator/glsl_fs_shader_gen.cpp
  src/video_core/shader/generator/glsl_fs_shader_gen.h
Labels: bug

#153 Update Android resolution setting interface
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement

#158 ci: Strip Clang binaries
  .ci/linux.sh
  .ci/windows.sh
Labels: size/XS
