Repository azahar-emu/azahar, pull requests merged in 2024-09, with the labels that each got.

#403 Cleanup previous PR
  src/lime_qt/main.cpp
Labels: size/XS

#415 Distribute MacOS build as a zip archive
  .ci/pack.sh
Labels: size/XS

#444 android: Make `Asynchronous shader compilation` non runtime editable
  src/android/app/src/main/java/io/github/lime3ds/android/features/settings/model/BooleanSetting.kt
Labels: size/XS

#459 Add a desktop shortcut toggle to a new page on the installer
  src/installer/lime3ds.nsi
Labels: enhancement, squash, size/M

#470 Revert "Android: Android 15 URI fixes"
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/HomeSettingsFragment.kt
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/Lime3DSDirectoryDialogFragment.kt
  src/android/app/src/main/java/io/github/lime3ds/android/fragments/SelectUserDirectoryDialogFragment.kt
  src/android/app/src/main/java/io/github/lime3ds/android/utils/FileUtil.kt
Labels: size/M

#454 lime_qt: Fix order of Texture Filter drop-down menu
  src/android/app/src/main/res/values/strings.xml
  src/lime_qt/configuration/configure_enhancements.ui
Labels: bug, size/XS
