Repository azahar-emu/azahar, pull requests merged in 2025-05, with the labels that each got.

#1004 citra_qt: Add scroll to layout page in graphics settings
  src/citra_qt/configuration/configure_layout.ui
Labels: enhancement, size/XXL

#808 android: Improve performance stats overlay settings and functionality
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/BooleanSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/Settings.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/EmulationMenuSettings.kt
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/drawable/ic_stats.xml
  src/android/app/src/main/res/layout/fragment_emulation.xml
  src/android/app/src/main/res/menu/menu_overlay_options.xml
  src/android/app/src/main/res/values-night/citra_colors.xml
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/citra_colors.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/L

#971 Make argument of `--username` required for `azahar-room`
  src/citra_room/citra_room.cpp
Labels: size/XS, miscellaneous

#1026 android: Fixed Turbo toast appearing in situations other than toggling Turbo
  src/android/app/src/main/java/org/citra/citra_emu/features/hotkeys/HotkeyUtility.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivityPresenter.kt
  src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/TurboHelper.kt
Labels: bug, size/S

#1041 file_util.cpp: Use _stat64 instead of stat where appropriate
  src/common/file_util.cpp
Labels: bug, size/S, rebase

#1035 video_core: Fixed Vulkan present mode being set incorrectly when emulation speed is unthrottled w/ vsync
  src/video_core/renderer_vulkan/vk_swapchain.cpp
Labels: bug, size/XS

#1047 Add setting to toggle RPC server (disabled by default)
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/BooleanSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/config.cpp
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/configuration/configure_debug.cpp
  src/citra_qt/configuration/configure_debug.ui
  src/common/settings.h
  src/core/core.cpp
Labels: size/M

#1056 Fix incorrect geo shader config start index parameter bit length
  src/video_core/pica/regs_pipeline.h
Labels: bug, size/XS

#1057 Allow SPIR-V when using Shadow2D texture mapping
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/shader/generator/pica_fs_config.h
  src/video_core/shader/generator/spv_fs_shader_gen.cpp
Labels: enhancement, size/S, self-reviewed

#998 renderer_vulkan: Update MoltenVK to 1.2.9
  CMakeModules/DownloadExternals.cmake
Labels: size/XS, miscellaneous

#820 android: Reorganize setup process to use multiple buttons per-page
  src/android/app/src/main/java/org/citra/citra_emu/adapters/SetupAdapter.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/CopyDirProgressDialogFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/SetupFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/SetupWarningDialogFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/model/SetupPage.kt
  src/android/app/src/main/java/org/citra/citra_emu/ui/main/MainActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/CitraDirectoryHelper.kt
  src/android/app/src/main/res/drawable/ic_permission.xml
  src/android/app/src/main/res/layout/page_button.xml
  src/android/app/src/main/res/layout/page_setup.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/XL

#1083 Add more advanced frame time information
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/jni/native.cpp
  src/citra_qt/citra_qt.cpp
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_ui.cpp
  src/citra_qt/configuration/configure_ui.ui
  src/citra_qt/uisettings.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/gsp/gsp_gpu.cpp
  src/core/perf_stats.cpp
  src/core/perf_stats.h
Labels: enhancement, size/L, self-reviewed

#1084 Fix disable spirv optimizer option not saving
  src/citra_qt/configuration/config.cpp
  src/common/settings.cpp
Labels: bug, size/XS, self-reviewed

#1093 kernel: Improve SVC handling timings
  src/core/hle/kernel/svc.cpp
Labels: enhancement, size/L
