Repository azahar-emu/azahar, pull requests merged in 2025-06, with the labels that each got.

#1129 frontend: Save RPC setting to config file
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_debug.cpp
  src/citra_sdl/config.cpp
Labels: size/XS, self-reviewed

#1130 vulkan: Report error code on Vulkan::CreateSurface
  src/video_core/renderer_vulkan/vk_platform.cpp
Labels: size/M, self-reviewed

#1134 ci: Correct Windows Vulkan SDK URL which was taken down by upstream
  .github/workflows/build.yml
Labels: bug, size/XS, self-reviewed

#1133 qt: Rename toggle console setting name to be more accurate
  src/citra_qt/configuration/configure_debug.ui
Labels: size/XS, miscellaneous, self-reviewed

#1142 android: Fix accurate multiplication setting using async shader value
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
Labels: bug, size/XS, self-reviewed

#1126 Replace deprecated and removed in boost 1.88 io_service to io_context
  src/input_common/udp/client.cpp
Labels: squash, size/S, refactor

#1123 android: Add landscape layout for setup pages
  src/android/app/src/main/res/layout-w600dp/page_setup.xml
Labels: enhancement, size/L

#1122 android: Fix hotkey presses opening nav drawer even after being bound
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/hotkeys/HotkeyUtility.kt
Labels: bug, squash, size/S

#1174 rasterizer: Increase uniform buffer size
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: size/XS

#1167 Fix aac_decoder memory leak
  src/audio_core/hle/aac_decoder.cpp
  src/audio_core/hle/aac_decoder.h
Labels: bug, squash, size/M

#1198 video_core: Fix LCD color fill
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_software/renderer_software.cpp
  src/video_core/renderer_software/renderer_software.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
Labels: size/M, self-reviewed

#1193 renderer_vulkan: Disable FIFO when refresh rate is lower than ~60hz or Apple low power mode is enabled
  .ci/license-header.rb
  CMakeLists.txt
  src/common/CMakeLists.txt
  src/common/apple_utils.h
  src/common/apple_utils.mm
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_present_window.cpp
  src/video_core/renderer_vulkan/vk_present_window.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
Labels: bug, squash, size/L

#1190 citra_sdl: Fix compile failure due to use of removed function
  src/citra_sdl/citra_sdl.cpp
Labels: bug, size/XS
