Repository azahar-emu/azahar, pull requests merged in 2025-03, with the labels that each got.

#583 Encrypt downloaded apps with a console unique key.
  src/citra_qt/configuration/configure_debug.cpp
  src/citra_qt/configuration/configure_system.cpp
  src/citra_qt/multiplayer/host_room.cpp
  src/citra_qt/multiplayer/lobby.cpp
  src/common/CMakeLists.txt
  src/common/file_util.cpp
  src/common/file_util.h
  src/core/cheats/gateway_cheat.cpp
  src/core/file_sys/ncch_container.cpp
  src/core/file_sys/ncch_container.h
  src/core/file_sys/romfs_reader.cpp
  src/core/file_sys/romfs_reader.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hw/unique_data.cpp
  src/core/hw/unique_data.h
  src/core/loader/3dsx.cpp
  src/core/loader/ncch.cpp
  src/video_core/pica/regs_shader.h
Labels: enhancement

#596 android: Disable 'Disable Right Eye Render' option by default
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
  src/android/app/src/main/jni/default_ini.h
Labels: bug

#598 Use NEON intrinsics in Vec4 dot operation
  src/common/vector_math.h
Labels: enhancement

#614 Change naming in builds and executables from citra to azahar
  CMakeLists.txt
  dist/dumpkeys/README.md
  src/citra_meta/CMakeLists.txt
Labels: bug, squash, size/S

#616 android: Updated AGP to 8.8.1 and Gradle to 8.10.2
  src/android/build.gradle.kts
  src/android/gradle/wrapper/gradle-wrapper.properties
Labels: size/XS, miscellaneous

#607 android: Replace `CITRA` username with `AZAHAR`
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
Labels: enhancement, size/S

#627 cmake: Add option `ENABLE_NATIVE_OPTIMIZATION`
  CMakeLists.txt
Labels: enhancement, size/S

#632 Remove .3ds from valid file extension list on MacOS
  dist/apple/Info.plist.in
Labels: size/XS

#638 qt: Implement migration prompt to bring data from Citra/Lime3DS
  src/citra_qt/citra_qt.cpp
  src/citra_qt/citra_qt.h
  src/common/common_paths.h
  src/common/file_util.cpp
  src/common/file_util.h
Labels: enhancement, squash, size/L

#642 Add 'Set Up System Files' option
  src/citra_qt/citra_qt.cpp
  src/citra_qt/citra_qt.h
  src/citra_qt/configuration/configure_system.cpp
  src/citra_qt/configuration/configure_system.h
  src/citra_qt/configuration/configure_system.ui
  src/citra_qt/main.ui
  src/common/settings.cpp
  src/common/settings.h
  src/core/core.cpp
  src/core/core.h
  src/core/hle/kernel/shared_page.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/am_net.cpp
  src/core/hle/service/am/am_u.cpp
  src/core/hle/service/cfg/cfg.cpp
  src/core/hle/service/cfg/cfg.h
  src/core/hle/service/fs/fs_user.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/nwm/nwm_uds.cpp
  src/core/hle/service/ptm/ptm.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/loader/artic.cpp
  src/core/loader/artic.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/perf_stats.cpp
  src/core/system_titles.cpp
  src/core/system_titles.h
  src/network/artic_base/artic_base_client.cpp
  src/network/artic_base/artic_base_client.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
Labels: enhancement, size/XXL

#651 Add cmake option to enable microprofile
  CMakeLists.txt
  externals/CMakeLists.txt
  src/citra_qt/citra_qt.cpp
  src/citra_qt/citra_qt.h
  src/citra_qt/debugger/profiler.cpp
  src/citra_qt/debugger/profiler.h
  src/video_core/renderer_opengl/gl_resource_manager.h
Labels: enhancement, size/M

#648 Do data migration before QtConfig is constructed
  src/citra_qt/CMakeLists.txt
  src/citra_qt/citra_qt.cpp
  src/citra_qt/citra_qt.h
  src/citra_qt/user_data_migration.cpp
  src/citra_qt/user_data_migration.h
Labels: bug, size/L

#653 Implement "Set Up System Files" on Android
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/DownloadSystemFilesDialogFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/HomeSettingsFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/SystemFilesFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/viewmodel/SystemFilesViewModel.kt
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/res/layout-w600dp/fragment_system_files.xml
  src/android/app/src/main/res/layout/fragment_system_files.xml
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/citra_qt.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/http/http_c.cpp
Labels: squash, size/XXL

#668 citra_qt.cpp: Make `isDarkMode()` compliant with QT 6.4 and older
  src/citra_qt/citra_qt.cpp
Labels: bug, size/XS

#679 am: Fix force new 3ds deviceID
  src/core/hle/service/am/am.cpp
Labels: bug, size/XS

#700 Fix artic traffic label being white on light theme
  src/citra_qt/citra_qt.cpp
Labels: size/XS

#697 Add support for uninitialized movable
  src/core/hw/unique_data.cpp
  src/core/hw/unique_data.h
Labels: size/M

#699 Implement framebuffer vertical flip flag
  src/common/math_util.h
  src/video_core/pica/regs_framebuffer.h
  src/video_core/pica/regs_rasterizer.h
  src/video_core/pica_types.h
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_cache/framebuffer_base.h
  src/video_core/rasterizer_cache/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/pica_to_vk.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/shader/generator/glsl_shader_gen.cpp
  src/video_core/shader/generator/shader_uniforms.h
Labels: bug, squash, size/L

#701 Fix uninitialized movable check on artic setup
  src/core/loader/artic.cpp
Labels: bug, size/S

#704 Fix VS uniform fields type declaration
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/shader/generator/shader_uniforms.h
Labels: size/S

#732 Fix incorrect syntax in construction of ARM_DynCom
  src/core/core.cpp
Labels: bug, size/XS

#729 Fix bug where log file was not generated on first run
  src/common/logging/backend.cpp
Labels: squash, size/XS

#749 cmake: Allow ENABLE_OPENGL option to be overridden on Linux aarch64
  CMakeLists.txt
Labels: size/S, miscellaneous

#738 Update files under dist to refer to Azahar instead of Citra
  CMakeLists.txt
  CMakeModules/BundleTarget.cmake
  dist/apple/azahar.icns
  dist/azahar-room.desktop
  dist/azahar.desktop
  dist/azahar.ico
  dist/azahar.manifest
  dist/azahar.svg
  dist/azahar.xml
  dist/qt_themes/default/icons/256x256/azahar.png
  dist/qt_themes/default/icons_light/256x256/azahar.png
  dist/qt_themes/default/theme_default.qrc
  src/citra_meta/CMakeLists.txt
  src/citra_meta/citra.rc
  src/citra_qt/aboutdialog.cpp
  src/citra_qt/aboutdialog.ui
  src/citra_qt/main.ui
  src/citra_room/citra_room.rc
  src/installer/citra.nsi
Labels: size/M, miscellaneous

#683 NSIS installer: Clean up Windows Start Menu entry
  src/installer/citra.nsi
Labels: size/S

#754 video_core: Fixed emulation window artefacts on OpenGL + Wayland
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: bug, size/XS

#756 Make AM:GetPersonalizedTicketInfoList only return personal tickets
  src/core/file_sys/ticket.cpp
  src/core/file_sys/ticket.h
  src/core/hle/service/am/am.cpp
Labels: size/L

#755 Show warning that 3ds files are no longer supported
  src/android/app/src/main/java/org/citra/citra_emu/fragments/GamesFragment.kt
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/configuration/config.cpp
  src/citra_qt/game_list.cpp
  src/citra_qt/game_list.h
  src/citra_qt/uisettings.h
Labels: size/M

#757 Change update URL to the website
  src/citra_qt/citra_qt.cpp
Labels: size/XS

#758 Fix temporary frame limit
  src/common/settings.h
  src/core/core.cpp
  src/core/hle/kernel/svc.cpp
Labels: size/XS

#773 Fix install CIA format string
  src/android/app/src/main/res/values/strings.xml
Labels: bug, priority - urgent

#775 Install 512x512 icon to CMAKE_INSTALL_PREFIX
  CMakeLists.txt
  CMakeModules/BundleTarget.cmake
  dist/azahar.png
Labels: size/XS, miscellaneous

#774 Make Android show unsupporetd encrypted app
  src/android/app/src/main/java/org/citra/citra_emu/model/GameInfo.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/GameHelper.kt
  src/android/app/src/main/jni/game_info.cpp
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, size/M

#750 Fix file read memory leak
  src/core/hle/service/fs/file.cpp
Labels: bug, squash, size/S

#714 Bump CMake MacOS compilation target to MacOS 13
  CMakeLists.txt
Labels: size/XS, miscellaneous

#602 Stereoscopic 3D Enhancements
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/citra_qt.cpp
  src/citra_qt/configuration/configure_enhancements.ui
  src/core/frontend/emu_window.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
Labels: enhancement, squash, size/L

#806 Fix fatal error caused by auto-detect region
  src/common/hacks/hack_list.cpp
  src/common/hacks/hack_list.h
  src/core/hle/service/apt/applet_manager.cpp
  src/core/hle/service/apt/apt.cpp
  src/core/hle/service/cfg/cfg.cpp
  src/core/hle/service/cfg/cfg.h
Labels: bug, priority - urgent, size/M

#603 android: Add Texture Sampling settings UI
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/configuration/configure_graphics.ui
Labels: enhancement, size/M

#844 Android: Fix missing audio when input device is set to none
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
Labels: size/XS

#840 Use reverse TLD filenames for installed Linux files where appropriate
  CMakeLists.txt
  CMakeModules/BundleTarget.cmake
  dist/azahar-room.desktop
  dist/azahar.desktop
  dist/org.azahar_emu.Azahar.xml
Labels: size/S, miscellaneous

#833 Mark console as "linked" when using the azahar artic setup tool
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/SystemFilesFragment.kt
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/res/layout/fragment_system_files.xml
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/citra_qt.cpp
  src/citra_qt/configuration/configure_system.cpp
  src/citra_qt/configuration/configure_system.h
  src/citra_qt/configuration/configure_system.ui
  src/core/hw/unique_data.cpp
  src/core/hw/unique_data.h
  src/core/loader/artic.cpp
  src/core/loader/artic.h
Labels: enhancement, squash, size/L

#847 Check that the country setting is valid for selected region
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsAdapter.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/SystemSaveGame.kt
  src/android/app/src/main/jni/system_save_game.cpp
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/configuration/configure_general.cpp
  src/citra_qt/configuration/configure_general.ui
  src/citra_qt/configuration/configure_system.cpp
  src/citra_qt/configuration/configure_system.h
  src/citra_qt/configuration/configure_system.ui
  src/core/hle/service/cfg/cfg.cpp
  src/core/hle/service/cfg/cfg.h
  src/core/loader/artic.cpp
  src/network/artic_base/artic_base_client.cpp
  src/network/artic_base/artic_base_client.h
  src/network/artic_base/artic_base_common.h
Labels: bug, squash, size/XL

#597 android: Implement Expand to Display Cutout option
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/BooleanSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/M

#809 android: Add game thumbnail to `EmulationFragment` nav drawer
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/res/layout/header_in_game.xml
Labels: enhancement, squash, size/M
