Repository azahar-emu/azahar, pull requests merged in 2025-09, with the labels that each got.

#1306 frontend: Improve consistency of capitalization and colon usage in UI
  src/android/app/src/main/res/values/strings.xml
  src/audio_core/sink.h
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_audio.ui
  src/citra_qt/configuration/configure_camera.ui
  src/citra_qt/configuration/configure_enhancements.ui
  src/citra_qt/configuration/configure_general.ui
  src/citra_qt/configuration/configure_graphics.ui
  src/citra_qt/configuration/configure_layout.ui
  src/citra_qt/configuration/configure_storage.ui
  src/citra_qt/configuration/configure_system.ui
  src/citra_qt/configuration/configure_ui.ui
  src/common/settings.h
Labels: size/L, miscellaneous

#1346 cmake: Add check for minimum AppleClang version
  CMakeLists.txt
Labels: bug, size/XS, self-reviewed

#1351 android: Bump Vulkan Validation Layers to SDK 1.4.313.0
  src/android/app/build.gradle.kts
Labels: size/XS, self-reviewed

#1352 macos: Set `UIDesignRequiresCompatibility` to true
  dist/apple/Info.plist.in
Labels: bug, size/XS, self-reviewed

#1354 Fix android termination bug
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/EmulationLifecycleUtil.kt
Labels: bug, squash, size/M

#1373 vk_pipeline_cache: Fix directory creation failure if `shaders/vulkan/` is missing
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
Labels: bug, size/S, self-reviewed
