Repository azahar-emu/azahar, pull requests merged in 2025-07, with the labels that each got.

#1218 GSP: correct MemoryFill interrupt signaling
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: size/S

#813 android: Implement play time tracking
  src/android/app/src/main/java/org/citra/citra_emu/CitraApplication.kt
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/adapters/GameAdapter.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/res/layout/dialog_about_game.xml
  src/citra_qt/CMakeLists.txt
  src/citra_qt/citra_qt.cpp
  src/citra_qt/game_list.h
  src/citra_qt/game_list_p.h
  src/citra_qt/game_list_worker.h
  src/citra_qt/util/util.cpp
  src/citra_qt/util/util.h
  src/common/CMakeLists.txt
  src/common/play_time_manager.cpp
  src/common/play_time_manager.h
Labels: enhancement, squash, size/L

#1165 Add missing find_package into CMakeLists.txt
  CMakeLists.txt
  src/citra_qt/CMakeLists.txt
Labels: squash, size/XS

#884 android: Added button sliding to button overlay
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.kt
  src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableButton.kt
  src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableDpad.kt
  src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlayDrawableJoystick.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/EmulationMenuSettings.kt
  src/android/app/src/main/res/menu/menu_overlay_options.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/L

#1249 Z3DS: Mark compressed files in UI and other minor fixes
  src/android/app/src/main/java/org/citra/citra_emu/adapters/GameAdapter.kt
  src/android/app/src/main/java/org/citra/citra_emu/model/Game.kt
  src/android/app/src/main/java/org/citra/citra_emu/model/GameInfo.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/GameHelper.kt
  src/android/app/src/main/jni/game_info.cpp
  src/android/app/src/main/res/layout/dialog_about_game.xml
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/configuration/configure_per_game.cpp
  src/citra_qt/game_list_worker.cpp
  src/core/loader/3dsx.cpp
  src/core/loader/3dsx.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/ncch.cpp
  src/core/loader/ncch.h
Labels: enhancement, size/L, self-reviewed

#1256 android: Upgrade to AGP 8.11.1, Gradle 8.13
  src/android/build.gradle.kts
  src/android/gradle/wrapper/gradle-wrapper.properties
Labels: size/XS, miscellaneous, self-reviewed

#1261 qt: Fix Azahar icon being accessed incorrectly in about + window icon
  src/citra_qt/aboutdialog.cpp
  src/citra_qt/aboutdialog.ui
  src/citra_qt/citra_qt.cpp
Labels: bug, size/S, self-reviewed
