Repository azahar-emu/azahar, pull requests merged in 2025-04, with the labels that each got.

#823 android: Add uninstall game/updates/dlc and open folder entries to about game dialog
  src/android/app/src/main/java/org/citra/citra_emu/adapters/GameAdapter.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/DocumentsTree.kt
  src/android/app/src/main/res/drawable/ic_open.xml
  src/android/app/src/main/res/drawable/ic_uninstall.xml
  src/android/app/src/main/res/layout/dialog_about_game.xml
  src/android/app/src/main/res/menu/game_context_menu_open.xml
  src/android/app/src/main/res/menu/game_context_menu_uninstall.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/L

#893 Suppress MSVC warnings C4711 and C5045 during compilation
  CMakeLists.txt
Labels: size/XS, miscellaneous

#877 qt: Various updates to the settings menu to improve consistency
  src/citra_qt/configuration/configure_general.cpp
  src/citra_qt/configuration/configure_input.cpp
  src/citra_qt/configuration/configure_layout.cpp
  src/citra_qt/configuration/configure_storage.cpp
  src/citra_qt/configuration/configure_system.cpp
  src/citra_qt/configuration/configure_system.ui
Labels: enhancement, size/M

#892 qt: Explicitly set window icon
  src/citra_qt/citra_qt.cpp
Labels: bug, size/XS

#901 Fix typo in README.md
  README.md
Labels: size/XS

#898 qt: For Qt 6.9.0 and above, use QImage::flipped over QImage::mirrored
  src/citra_qt/bootmanager.cpp
  src/citra_qt/camera/camera_util.cpp
  src/citra_qt/util/util.cpp
  src/citra_qt/util/util.h
Labels: bug, squash, size/M

#810 android: Update emulation_pause icon on resume
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
Labels: bug, size/XS

#606 android: Implement support for automatic resolution scale
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, size/XS

#605 Add `turbo speed` hotkey
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/hotkeys/Hotkey.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/hotkeys/HotkeyFunctions.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/hotkeys/HotkeyUtility.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/Settings.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/InputBindingSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/config.cpp
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/citra_qt.cpp
  src/citra_qt/citra_qt.h
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/config.h
  src/citra_qt/configuration/configure_dialog.cpp
  src/citra_qt/configuration/configure_general.cpp
  src/citra_qt/configuration/configure_general.h
  src/citra_qt/configuration/configure_general.ui
  src/citra_qt/configuration/configure_hotkeys.cpp
  src/citra_qt/configuration/configure_per_game.cpp
  src/common/settings.h
Labels: enhancement, squash, size/L

#814 android: Add isEnabled setting item conditional check
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/SettingsItem.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsAdapter.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/DateTimeViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/InputBindingSettingViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/RunnableViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/SingleChoiceViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/SliderViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/StringInputViewHolder.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/SwitchSettingViewHolder.kt
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/L

#807 framebuffer: Add hybrid layout mode to FrameLayoutFromResolutionScale
  src/core/frontend/framebuffer_layout.cpp
Labels: bug, squash, size/S

#811 qt: Add quicksave / quickload hotkeys
  src/citra_qt/citra_qt.cpp
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/config.h
  src/citra_qt/main.ui
Labels: enhancement, squash, size/M

#625 android: Original Portrait Layout
  src/android/app/src/main/java/org/citra/citra_emu/display/ScreenLayout.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/res/menu/menu_portrait_screen_layout.xml
  src/android/app/src/main/res/values/arrays.xml
  src/common/settings.h
  src/core/frontend/emu_window.cpp
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
Labels: enhancement, squash, size/M

#911 android: Add turbo speed hotkey touch controls overlay button
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.kt
  src/android/app/src/main/res/drawable-hdpi/button_turbo.png
  src/android/app/src/main/res/drawable-hdpi/button_turbo_pressed.png
  src/android/app/src/main/res/drawable-xhdpi/button_turbo.png
  src/android/app/src/main/res/drawable-xhdpi/button_turbo_pressed.png
  src/android/app/src/main/res/drawable-xxhdpi/button_turbo.png
  src/android/app/src/main/res/drawable-xxhdpi/button_turbo_pressed.png
  src/android/app/src/main/res/drawable-xxxhdpi/button_turbo.png
  src/android/app/src/main/res/drawable-xxxhdpi/button_turbo_pressed.png
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/integers.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/M

#920 Use common open source font on CHN/KOR/TWN
  src/core/file_sys/archive_ncch.cpp
  src/core/hle/service/apt/apt.cpp
Labels: size/S

#921 Fix system files setup for region changed consoles
  src/citra_qt/configuration/configure_system.cpp
  src/core/hw/unique_data.cpp
  src/core/hw/unique_data.h
  src/core/loader/artic.h
  src/core/system_titles.cpp
Labels: bug, size/L

#917 android: Lime3DS to Azahar migration adjustments
  src/android/app/src/main/java/org/citra/citra_emu/fragments/SelectUserDirectoryDialogFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/fragments/UpdateUserDirectoryDialogFragment.kt
  src/android/app/src/main/java/org/citra/citra_emu/ui/main/MainActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/utils/CitraDirectoryUtils.kt
  src/android/app/src/main/res/layout/dialog_select_which_directory.xml
  src/android/app/src/main/res/values/strings.xml
Labels: enhancement, squash, size/L

#929 android: Disable title bar on Android 9
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
Labels: bug, size/XS

#930 Fix ncch loader building wrong update title ID
  src/core/hle/service/am/am.cpp
  src/core/loader/ncch.cpp
Labels: size/S

#935 Qt: set desktop filename and organization domain #934
  src/citra_qt/citra_qt.cpp
Labels: size/XS

#622 Implement screen gap setting
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/config.cpp
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/res/values/strings.xml
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_layout.cpp
  src/citra_qt/configuration/configure_layout.ui
  src/common/settings.cpp
  src/common/settings.h
  src/core/frontend/framebuffer_layout.cpp
Labels: enhancement, squash, size/L

#944 android: Restructure strings.xml
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/res/values/strings.xml
Labels: size/M, refactor

#952 Fix File::Write() not conforming to debug header validation
  src/core/hle/service/fs/file.cpp
Labels: size/XS

#958 Add Swedish to citra.nsi
  src/installer/citra.nsi
Labels: size/XS

#955 Fallback to silence when no samples have been captured.
  src/audio_core/cubeb_input.cpp
  src/audio_core/input.h
  src/audio_core/null_input.h
  src/audio_core/openal_input.cpp
Labels: size/M

#945 citra_qt: Fix duplicated hotkey entry and order.
  src/citra_qt/configuration/config.cpp
Labels: bug, squash, size/XS

#950 Support downloading owned DLCs
  src/core/file_sys/cia_container.cpp
  src/core/file_sys/cia_container.h
  src/core/file_sys/ticket.cpp
  src/core/file_sys/ticket.h
  src/core/file_sys/title_metadata.cpp
  src/core/file_sys/title_metadata.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/am_net.cpp
Labels: enhancement, size/XXL

#956 Fix cheats and rpc server affecting the wrong processes
  dist/scripting/citra.py
  src/core/cheats/cheat_base.h
  src/core/cheats/cheats.cpp
  src/core/cheats/cheats.h
  src/core/cheats/gateway_cheat.cpp
  src/core/cheats/gateway_cheat.h
  src/core/core.cpp
  src/core/memory.cpp
  src/core/memory.h
  src/core/rpc/packet.h
  src/core/rpc/rpc_server.cpp
  src/core/rpc/rpc_server.h
Labels: bug, size/L

#978 Allow shader cache to switch to different titles at runtime
  src/android/app/src/main/jni/native.cpp
  src/citra_qt/bootmanager.cpp
  src/citra_qt/bootmanager.h
  src/citra_qt/citra_qt.cpp
  src/citra_qt/citra_qt.h
  src/citra_qt/loading_screen.cpp
  src/citra_qt/loading_screen.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/gsp/gsp_gpu.cpp
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: enhancement, size/L

#977 Fix off-by-one error in savestates that could cause crashes
  src/citra_qt/citra_qt.cpp
Labels: bug, priority - high, size/XS

#979 Fix installing DLCs with encrypted flags for missing contents
  src/core/file_sys/cia_container.cpp
  src/core/file_sys/cia_container.h
  src/core/file_sys/title_metadata.cpp
  src/core/file_sys/title_metadata.h
  src/core/hle/service/am/am.cpp
Labels: bug, size/L

#984 Updating minimum macOS target to 13.4 to avoid breaking macOS builds
  CMakeLists.txt
Labels: size/XS

#994 qt: Add new update checker logic which correctly handles prereleases
  src/citra_qt/citra_qt.cpp
  src/citra_qt/update_checker.cpp
  src/citra_qt/update_checker.h
Labels: bug, size/M
