Repository azahar-emu/azahar, pull requests merged in 2025-08, with the labels that each got.

#1262 Use MacOS-specific refresh rate check to avoid SDL race condition
  src/common/apple_utils.h
  src/common/apple_utils.mm
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
Labels: bug, squash, size/M

#1264 ci: Dropped iOS build job
  .github/workflows/build.yml
Labels: size/S, miscellaneous, self-reviewed

#617 android: Implement secondary display support
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
  src/android/app/src/main/java/org/citra/citra_emu/display/ScreenLayout.kt
  src/android/app/src/main/java/org/citra/citra_emu/display/SecondaryDisplay.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/jni/config.cpp
  src/android/app/src/main/jni/default_ini.h
  src/android/app/src/main/jni/emu_window/emu_window.cpp
  src/android/app/src/main/jni/emu_window/emu_window.h
  src/android/app/src/main/jni/emu_window/emu_window_gl.cpp
  src/android/app/src/main/jni/emu_window/emu_window_gl.h
  src/android/app/src/main/jni/emu_window/emu_window_vk.cpp
  src/android/app/src/main/jni/emu_window/emu_window_vk.h
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
  src/common/settings.cpp
  src/common/settings.h
  src/core/frontend/emu_window.cpp
  src/core/frontend/emu_window.h
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
  src/video_core/renderer_base.cpp
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
Labels: enhancement, squash, size/XL

#1295 qt: Prerelease builds now direct users to upgrade via GitHub rather than azahar-emu.org
  src/citra_qt/citra_qt.cpp
Labels: enhancement, size/S, self-reviewed

#1342 cmake: Corrected widespread incorrect usage of the SYSTEM property
  externals/CMakeLists.txt
Labels: bug, size/M, self-reviewed
