Repository azahar-emu/azahar, pull requests merged in 2025-10, with the labels that each got.

#1410 ci: Update all macOS runners to macOS 15 Sequoia
  .github/workflows/build.yml
Labels: size/XS, miscellaneous, self-reviewed

#1341 Android: Dual screen fixes for Handhelds that have 2 screens like Ayaneo Pocket DS
  src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/citra/citra_emu/display/SecondaryDisplay.kt
  src/android/app/src/main/java/org/citra/citra_emu/overlay/InputOverlay.kt
  src/android/app/src/main/jni/native.cpp
  src/core/frontend/emu_window.cpp
Labels: bug, squash, size/L

#1371 Android: Add Display Listener methods for smoother secondary display updates
  src/android/app/src/main/java/org/citra/citra_emu/display/SecondaryDisplay.kt
Labels: bug, size/S, self-reviewed
